version: '3.8'

services:
  backend:
    build: ./backend
    ports:
    - 4000:4000
    volumes:
      - ./backend/src:/app/src/
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true


  frontend:
    build: ./frontend-webapp
    ports:
      - 3000:3000
    volumes:
      - ./frontend-webapp/src:/app/src/
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
