version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - CHOKIDAR_USEPOLLING=true
    ports:
    - 4000:4000
    volumes:
      - ./backend/src:/app/src/
      - /app/node_modules

  frontend:
    build: ./frontend-webapp
    ports:
      - 3000:3000
    volumes:
      - ./frontend-webapp/src:/app/src/
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - database-content:/var/lib/postgresql/data
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database-content: